server:
   port: ${port:9000}

 
zuul:
  #Service will be mapped under the /api URI .
# prefix: /api
#  ignoredServices: '*'
  routes:
    app-by-url:
      path: /router/**
      url: http://localhost:9001
      stripPrefix: false
    

spring:
  application:
    name: zuul-proxy-server

logging:
  level: 
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
 
eureka:
  client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone: http://localhost:9761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
